// Distractors usually describe a service instead of naming it, so these phrases map a
// description back to a glossary entry.
export const DESCRIPTORS = [
  { name: "AWS Config", phrases: ["configuration change", "resource configuration", "configuration history", "configuration compliance", "inventory of resource"] },
  { name: "AWS CloudTrail", phrases: ["api call", "who made", "user activity", "account activity", "audit trail", "api activity"] },
  { name: "Amazon CloudWatch", phrases: ["metric", "utilization data", "alarm", "operational data", "performance data"] },
  { name: "AWS Trusted Advisor", phrases: ["optimization recommendation", "best practice recommendation", "cost optimization recommendation", "security optimization"] },
  { name: "AWS Direct Connect", phrases: ["point-to-point connectivity", "dedicated network connection", "dedicated private connection", "private connection between an on-premises"] },
  { name: "Amazon Route 53", phrases: ["dns configuration", "domain name system", "domain registration", "routing type"] },
  { name: "Amazon CloudFront", phrases: ["cache content", "cached copies", "content delivery", "deliver content to users", "edge caching"] },
  { name: "Amazon S3", phrases: ["object storage", "store objects", "unlimited storage", "store and retrieve any amount of data"] },
  { name: "Amazon EBS", phrases: ["block storage", "block level storage", "persistent storage for a single", "attach to a single instance"] },
  { name: "Amazon EFS", phrases: ["shared file system", "file storage that can be mounted", "shared across multiple instances"] },
  { name: "Amazon RDS", phrases: ["managed relational database", "relational database"] },
  { name: "Amazon DynamoDB", phrases: ["key-value", "key value store", "nosql database"] },
  { name: "Amazon Redshift", phrases: ["data warehouse", "data warehousing", "business intelligence workload"] },
  { name: "AWS Lambda", phrases: ["run code without provisioning", "without managing servers", "event-driven code", "pay only for compute time"] },
  { name: "Auto Scaling", phrases: ["automatically provisioning new resources", "add or remove capacity", "adjust capacity to maintain", "scale automatically to meet demand"] },
  { name: "Elastic Load Balancing", phrases: ["distribute incoming traffic", "distributes traffic", "spread traffic across", "route traffic to healthy"] },
  { name: "AWS IAM", phrases: ["who can access", "control access to aws resources", "manage users and permissions", "authentication and authorization"] },
  { name: "multi-factor authentication", phrases: ["second form of authentication", "one-time password", "additional authentication factor"] },
  { name: "AWS KMS", phrases: ["create and manage encryption keys", "manage cryptographic keys", "encryption key management"] },
  { name: "AWS Shield", phrases: ["ddos", "denial of service"] },
  { name: "AWS WAF", phrases: ["sql injection", "cross-site scripting", "filter web traffic", "block malicious requests"] },
  { name: "Amazon GuardDuty", phrases: ["threat detection", "detect malicious activity", "unusual behaviour", "unusual behavior"] },
  { name: "Amazon Inspector", phrases: ["vulnerability", "security assessment", "scan for known vulnerabilities"] },
  { name: "Amazon Macie", phrases: ["sensitive data", "personally identifiable information", "discover and classify data"] },
  { name: "AWS Artifact", phrases: ["compliance report", "audit report", "soc report", "iso certification"] },
  { name: "AWS Organizations", phrases: ["multiple aws accounts", "manage several accounts", "centrally manage accounts"] },
  { name: "consolidated billing", phrases: ["single bill", "one bill for multiple", "combined billing"] },
  { name: "AWS Cost Explorer", phrases: ["visualize cost", "analyse spending", "analyze spending", "view historical cost", "forecast future cost"] },
  { name: "AWS Budgets", phrases: ["alert when spending", "set a spending threshold", "notify when costs exceed", "budget threshold"] },
  { name: "cost allocation tags", phrases: ["categorize spending", "track spending by", "categorise spending", "group costs by"] },
  { name: "AWS CloudFormation", phrases: ["infrastructure as code", "template to provision", "declarative template", "provision resources from a template"] },
  { name: "AWS Elastic Beanstalk", phrases: ["upload your code and", "deploy code without managing the infrastructure", "handles capacity provisioning and load balancing"] },
  { name: "Amazon SQS", phrases: ["message queue", "decouple components", "queue messages"] },
  { name: "Amazon SNS", phrases: ["publish and subscribe", "send notifications", "pub/sub", "topic subscribers"] },
  { name: "AWS Snowball", phrases: ["physical device to transfer", "ship data", "petabyte-scale data transfer"] },
  { name: "AWS Storage Gateway", phrases: ["hybrid storage", "on-premises access to cloud storage"] },
  { name: "Amazon S3 Glacier", phrases: ["long-term archive", "archival storage", "rarely accessed data", "long term data archiving"] },
  { name: "AWS Support plans", phrases: ["response time", "24x7 access to", "technical support"] },
  { name: "AWS Professional Services", phrases: ["paid engagement", "consulting engagement"] },
  { name: "AWS Marketplace", phrases: ["third-party software", "digital catalog", "purchase software"] },
  { name: "Availability Zone", phrases: ["isolated location within a region", "discrete data cent"] },
  { name: "edge location", phrases: ["closer to end users", "closest location to the user"] },
  { name: "Amazon VPC", phrases: ["isolated network", "logically isolated section", "define your own ip range"] },
  { name: "AWS Systems Manager", phrases: ["patch instances", "operational data across", "run commands on instances"] },
  { name: "Amazon Aurora", phrases: ["five times the throughput", "mysql and postgresql compatible"] },
  { name: "Amazon ElastiCache", phrases: ["in-memory cache", "in memory data store", "cache frequently accessed"] },
  { name: "Spot Instances", phrases: ["spare capacity", "interrupted with two minutes", "up to 90% discount"] },
  { name: "Reserved Instances", phrases: ["one-year or three-year", "commit to a specific instance", "1-year or 3-year term"] },
  { name: "Savings Plans", phrases: ["commit to a consistent amount", "consistent hourly spend"] },
  { name: "AWS Free Tier", phrases: ["free of charge for 12 months", "always free"] },
];
