export const DOMAINS = [
  { name: "Cloud Concepts", weight: 24 },
  { name: "Security and Compliance", weight: 30 },
  { name: "Cloud Technology and Services", weight: 34 },
  { name: "Billing, Pricing, and Support", weight: 12 },
];

const CONCEPT = "Cloud Concepts";
const SECURITY = "Security and Compliance";
const TECH = "Cloud Technology and Services";
const BILLING = "Billing, Pricing, and Support";

export const GLOSSARY = [
  {
    name: "Amazon EC2",
    match: ["amazon ec2", "aws ec2", "ec2 instance", "elastic compute cloud", "ec2"],
    domain: TECH,
    topic: "Compute",
    blurb: "resizable virtual machines where you choose the instance type, control the guest operating system, and pay per second or hour of runtime",
  },
  {
    name: "AWS Lambda",
    match: ["aws lambda", "lambda function", "lambda"],
    domain: TECH,
    topic: "Serverless compute",
    blurb: "runs code in response to events with no servers to manage, scales automatically, and bills only for the milliseconds the code executes",
  },
  {
    name: "AWS Fargate",
    match: ["aws fargate", "fargate"],
    domain: TECH,
    topic: "Containers",
    blurb: "a serverless compute engine for containers that removes the need to provision or manage the EC2 instances behind ECS and EKS",
  },
  {
    name: "Amazon ECS",
    match: ["amazon ecs", "elastic container service", "ecs"],
    domain: TECH,
    topic: "Containers",
    blurb: "AWS-native container orchestration that schedules and runs Docker containers across a cluster",
  },
  {
    name: "Amazon EKS",
    match: ["amazon eks", "elastic kubernetes service", "eks"],
    domain: TECH,
    topic: "Containers",
    blurb: "managed Kubernetes, used when a team wants the standard Kubernetes API rather than an AWS-specific scheduler",
  },
  {
    name: "Amazon ECR",
    match: ["amazon ecr", "elastic container registry", "ecr"],
    domain: TECH,
    topic: "Containers",
    blurb: "a private registry for storing, versioning and scanning Docker container images",
  },
  {
    name: "Amazon Lightsail",
    match: ["amazon lightsail", "lightsail"],
    domain: TECH,
    topic: "Compute",
    blurb: "pre-configured virtual private servers with a simple fixed monthly price, aimed at small workloads and users new to AWS",
  },
  {
    name: "AWS Batch",
    match: ["aws batch"],
    domain: TECH,
    topic: "Compute",
    blurb: "runs long-running batch computing jobs by provisioning the right amount of compute and queuing work, with no job duration limit",
  },
  {
    name: "AWS Elastic Beanstalk",
    match: ["elastic beanstalk", "beanstalk"],
    domain: TECH,
    topic: "Deployment",
    blurb: "uploads your application code and automatically provisions the capacity, load balancing, scaling and health monitoring behind it",
  },
  {
    name: "AWS Outposts",
    match: ["aws outposts", "outposts"],
    domain: TECH,
    topic: "Hybrid infrastructure",
    blurb: "physical racks of AWS hardware installed in your own data centre so you can run AWS services on premises",
  },
  {
    name: "AWS Local Zones",
    match: ["local zones", "local zone"],
    domain: CONCEPT,
    topic: "Global infrastructure",
    blurb: "extensions of a Region placed near large population centres to deliver single-digit millisecond latency",
  },
  {
    name: "AWS Wavelength",
    match: ["wavelength"],
    domain: TECH,
    topic: "Global infrastructure",
    blurb: "embeds AWS compute inside 5G telecom networks for ultra-low-latency mobile applications",
  },
  {
    name: "Amazon S3",
    match: ["amazon s3", "aws s3", "simple storage service", "s3 bucket", "s3"],
    domain: TECH,
    topic: "Object storage",
    blurb: "durable object storage for any amount of unstructured data, with versioning, lifecycle rules and eleven nines of durability",
  },
  {
    name: "Amazon S3 Glacier",
    match: ["s3 glacier", "amazon glacier", "glacier deep archive", "glacier"],
    domain: TECH,
    topic: "Archival storage",
    blurb: "the lowest-cost S3 storage classes for archives, trading minutes-to-hours retrieval time for a very low price per gigabyte",
  },
  {
    name: "S3 Intelligent-Tiering",
    match: ["intelligent-tiering", "intelligent tiering"],
    domain: BILLING,
    topic: "Storage cost optimisation",
    blurb: "moves objects between access tiers automatically based on observed usage, so you save money without knowing the access pattern in advance",
  },
  {
    name: "Amazon EBS",
    match: ["amazon ebs", "elastic block store", "ebs volume", "ebs"],
    domain: TECH,
    topic: "Block storage",
    blurb: "network-attached block volumes for a single EC2 instance, behaving like a virtual hard disk that persists independently of the instance",
  },
  {
    name: "Amazon EFS",
    match: ["amazon efs", "elastic file system", "efs"],
    domain: TECH,
    topic: "File storage",
    blurb: "a managed NFS file system that many EC2 instances across multiple Availability Zones can mount at the same time",
  },
  {
    name: "Amazon FSx",
    match: ["amazon fsx", "fsx"],
    domain: TECH,
    topic: "File storage",
    blurb: "managed third-party file systems such as Windows File Server and Lustre for workloads that need those specific protocols",
  },
  {
    name: "EC2 instance store",
    match: ["instance store", "instance storage"],
    domain: TECH,
    topic: "Block storage",
    blurb: "physically attached ephemeral disk that delivers very high IOPS but loses all data when the instance stops or terminates",
  },
  {
    name: "AWS Storage Gateway",
    match: ["storage gateway"],
    domain: TECH,
    topic: "Hybrid storage",
    blurb: "an on-premises appliance that presents local NFS, SMB or iSCSI storage while backing the data into AWS",
  },
  {
    name: "AWS Snowball",
    match: ["snowball edge", "snowball", "snowmobile", "snowcone", "snow family"],
    domain: TECH,
    topic: "Data migration",
    blurb: "ruggedised physical devices shipped to your site to transfer petabyte-scale data when the network would take too long",
  },
  {
    name: "AWS DataSync",
    match: ["datasync"],
    domain: TECH,
    topic: "Data migration",
    blurb: "automates and accelerates online data transfer between on-premises storage and AWS storage services",
  },
  {
    name: "AWS Backup",
    match: ["aws backup"],
    domain: TECH,
    topic: "Backup and recovery",
    blurb: "centrally schedules, enforces and audits backups across many AWS services from one policy",
  },
  {
    name: "Amazon RDS",
    match: ["amazon rds", "aws rds", "relational database service", "rds"],
    domain: TECH,
    topic: "Relational databases",
    blurb: "managed relational databases where AWS handles provisioning, patching, backups and failover for engines such as MySQL, PostgreSQL and SQL Server",
  },
  {
    name: "Amazon Aurora",
    match: ["amazon aurora", "aurora serverless", "aurora"],
    domain: TECH,
    topic: "Relational databases",
    blurb: "an AWS-built database compatible with MySQL and PostgreSQL that delivers much higher throughput and replicates storage across three Availability Zones",
  },
  {
    name: "Amazon DynamoDB",
    match: ["amazon dynamodb", "dynamodb"],
    domain: TECH,
    topic: "NoSQL databases",
    blurb: "a serverless key-value NoSQL database with single-digit millisecond latency at any scale and no servers to manage",
  },
  {
    name: "Amazon Redshift",
    match: ["amazon redshift", "redshift"],
    domain: TECH,
    topic: "Analytics",
    blurb: "a petabyte-scale data warehouse built for complex analytical queries and business intelligence reporting, not for transactional workloads",
  },
  {
    name: "Amazon ElastiCache",
    match: ["elasticache"],
    domain: TECH,
    topic: "Caching",
    blurb: "managed Redis or Memcached used to cache frequent queries in memory and take read pressure off a database",
  },
  {
    name: "Amazon DocumentDB",
    match: ["documentdb"],
    domain: TECH,
    topic: "NoSQL databases",
    blurb: "a managed document database compatible with MongoDB workloads",
  },
  {
    name: "Amazon Neptune",
    match: ["neptune"],
    domain: TECH,
    topic: "NoSQL databases",
    blurb: "a managed graph database for highly connected data such as social networks, fraud rings and recommendation engines",
  },
  {
    name: "Amazon QLDB",
    match: ["qldb", "quantum ledger"],
    domain: TECH,
    topic: "Specialised databases",
    blurb: "an immutable, cryptographically verifiable ledger database for recording an unalterable history of changes",
  },
  {
    name: "Amazon Athena",
    match: ["amazon athena", "athena"],
    domain: TECH,
    topic: "Analytics",
    blurb: "runs standard SQL directly against files in Amazon S3 with no infrastructure to run, billed per terabyte scanned",
  },
  {
    name: "Amazon EMR",
    match: ["amazon emr", "elastic mapreduce", "emr"],
    domain: TECH,
    topic: "Analytics",
    blurb: "managed Hadoop, Spark and Presto clusters for large-scale data processing",
  },
  {
    name: "AWS Glue",
    match: ["aws glue", "glue"],
    domain: TECH,
    topic: "Analytics",
    blurb: "a serverless extract, transform and load service that also catalogues data schemas for other analytics tools",
  },
  {
    name: "Amazon QuickSight",
    match: ["quicksight"],
    domain: TECH,
    topic: "Analytics",
    blurb: "a serverless business intelligence service for building dashboards and visualisations from AWS data sources",
  },
  {
    name: "Amazon Kinesis",
    match: ["amazon kinesis", "kinesis"],
    domain: TECH,
    topic: "Streaming data",
    blurb: "collects and processes streaming data such as clickstreams, logs and telemetry in real time",
  },
  {
    name: "Amazon MSK",
    match: ["amazon msk", "managed streaming for apache kafka"],
    domain: TECH,
    topic: "Streaming data",
    blurb: "fully managed Apache Kafka clusters for teams already standardised on Kafka",
  },
  {
    name: "Amazon VPC",
    match: ["amazon vpc", "virtual private cloud", "vpc"],
    domain: TECH,
    topic: "Networking",
    blurb: "a logically isolated private network in AWS where you define the IP range, subnets, route tables and gateways",
  },
  {
    name: "security group",
    match: ["security group"],
    domain: SECURITY,
    topic: "Network security",
    blurb: "a stateful virtual firewall attached to an instance network interface that supports allow rules only, with return traffic permitted automatically",
  },
  {
    name: "network ACL",
    match: ["network acl", "network access control list", "nacl"],
    domain: SECURITY,
    topic: "Network security",
    blurb: "a stateless filter evaluated at the subnet boundary that supports both allow and deny rules and needs explicit rules in each direction",
  },
  {
    name: "Elastic Load Balancing",
    match: ["elastic load balanc", "application load balancer", "network load balancer", "load balancer", "elb"],
    domain: TECH,
    topic: "Networking",
    blurb: "distributes incoming traffic across healthy targets in multiple Availability Zones and stops sending requests to instances that fail health checks",
  },
  {
    name: "Auto Scaling",
    match: ["auto scaling group", "auto scaling", "autoscaling"],
    domain: TECH,
    topic: "Elasticity",
    blurb: "adds and removes EC2 capacity automatically in response to demand, which is how elasticity is implemented in practice",
  },
  {
    name: "Amazon CloudFront",
    match: ["cloudfront"],
    domain: TECH,
    topic: "Content delivery",
    blurb: "a content delivery network that caches content at edge locations worldwide to cut latency and offload the origin",
  },
  {
    name: "Amazon Route 53",
    match: ["route 53", "route53"],
    domain: TECH,
    topic: "Networking",
    blurb: "a managed DNS service that also registers domains, performs health checks and supports latency, geolocation and failover routing",
  },
  {
    name: "AWS Direct Connect",
    match: ["direct connect"],
    domain: TECH,
    topic: "Hybrid networking",
    blurb: "a dedicated private physical link between a data centre and AWS that bypasses the public internet for consistent bandwidth and latency",
  },
  {
    name: "AWS Site-to-Site VPN",
    match: ["site-to-site vpn", "site to site vpn", "vpn connection", "vpn"],
    domain: TECH,
    topic: "Hybrid networking",
    blurb: "an encrypted tunnel between an on-premises network and a VPC over the public internet, quick to set up but subject to internet variability",
  },
  {
    name: "AWS Transit Gateway",
    match: ["transit gateway"],
    domain: TECH,
    topic: "Networking",
    blurb: "a central hub that connects many VPCs and on-premises networks without building a mesh of individual peering connections",
  },
  {
    name: "VPC endpoint",
    match: ["vpc endpoint", "privatelink"],
    domain: TECH,
    topic: "Networking",
    blurb: "lets resources in a VPC reach AWS services over the AWS private network instead of traversing the internet",
  },
  {
    name: "VPC peering",
    match: ["vpc peering"],
    domain: TECH,
    topic: "Networking",
    blurb: "a private one-to-one network link between two VPCs, which does not support transitive routing",
  },
  {
    name: "NAT gateway",
    match: ["nat gateway", "nat instance"],
    domain: TECH,
    topic: "Networking",
    blurb: "allows instances in a private subnet to make outbound internet connections while blocking inbound connections from the internet",
  },
  {
    name: "internet gateway",
    match: ["internet gateway"],
    domain: TECH,
    topic: "Networking",
    blurb: "the VPC component that enables two-way communication between resources in a public subnet and the internet",
  },
  {
    name: "AWS Global Accelerator",
    match: ["global accelerator"],
    domain: TECH,
    topic: "Networking",
    blurb: "routes user traffic onto the AWS global network at the nearest edge location and provides static anycast IP addresses",
  },
  {
    name: "AWS IAM",
    match: ["identity and access management", "aws iam", "iam user", "iam role", "iam policy", "iam group", "iam"],
    domain: SECURITY,
    topic: "Identity and access",
    blurb: "controls who is authenticated and what they are authorised to do, using users, groups, roles and JSON policies, at no additional cost",
  },
  {
    name: "IAM role",
    match: ["iam role", "service role"],
    domain: SECURITY,
    topic: "Identity and access",
    blurb: "an identity assumed temporarily to obtain short-lived credentials, which is the correct way to give an application or service permissions without storing access keys",
  },
  {
    name: "multi-factor authentication",
    match: ["multi-factor authentication", "multi factor authentication", "mfa"],
    domain: SECURITY,
    topic: "Identity and access",
    blurb: "requires a second factor in addition to the password, and is the single highest-value control to apply to the root user",
  },
  {
    name: "AWS IAM Identity Center",
    match: ["iam identity center", "aws single sign-on", "aws sso"],
    domain: SECURITY,
    topic: "Federation",
    blurb: "provides single sign-on across multiple AWS accounts and connects to an existing corporate directory so users keep one set of credentials",
  },
  {
    name: "Amazon Cognito",
    match: ["cognito"],
    domain: SECURITY,
    topic: "Federation",
    blurb: "handles sign-up, sign-in and identity federation for the end users of your web and mobile applications, not for AWS console access",
  },
  {
    name: "AWS STS",
    match: ["security token service", "aws sts"],
    domain: SECURITY,
    topic: "Identity and access",
    blurb: "issues the temporary, limited-privilege credentials returned whenever a role is assumed",
  },
  {
    name: "AWS Directory Service",
    match: ["directory service", "managed microsoft ad", "active directory"],
    domain: SECURITY,
    topic: "Federation",
    blurb: "runs or connects to Microsoft Active Directory so existing directory identities can be used with AWS resources",
  },
  {
    name: "AWS KMS",
    match: ["key management service", "aws kms", "kms"],
    domain: SECURITY,
    topic: "Encryption",
    blurb: "creates and controls the encryption keys used by integrated AWS services for encryption at rest, with every key use logged to CloudTrail",
  },
  {
    name: "AWS CloudHSM",
    match: ["cloudhsm"],
    domain: SECURITY,
    topic: "Encryption",
    blurb: "dedicated single-tenant hardware security modules for cases where regulation requires you to hold the keys with no AWS access at all",
  },
  {
    name: "AWS Certificate Manager",
    match: ["certificate manager", "acm"],
    domain: SECURITY,
    topic: "Encryption in transit",
    blurb: "provisions and automatically renews the TLS certificates used by load balancers, CloudFront and API Gateway, at no charge for public certificates",
  },
  {
    name: "AWS Secrets Manager",
    match: ["secrets manager"],
    domain: SECURITY,
    topic: "Credential management",
    blurb: "stores secrets such as database passwords and rotates them automatically on a schedule without requiring an application redeployment",
  },
  {
    name: "AWS Shield",
    match: ["aws shield", "shield advanced", "shield standard", "shield"],
    domain: SECURITY,
    topic: "DDoS protection",
    blurb: "defends against distributed denial of service attacks, with the Standard tier enabled free for every account and Advanced adding response team access and cost protection",
  },
  {
    name: "AWS WAF",
    match: ["web application firewall", "aws waf", "waf"],
    domain: SECURITY,
    topic: "Application security",
    blurb: "filters HTTP and HTTPS requests at the application layer to block patterns such as SQL injection and cross-site scripting before they reach the application",
  },
  {
    name: "AWS Firewall Manager",
    match: ["firewall manager"],
    domain: SECURITY,
    topic: "Application security",
    blurb: "centrally applies and enforces WAF, Shield Advanced and security group rules across every account in an organization",
  },
  {
    name: "AWS Network Firewall",
    match: ["network firewall"],
    domain: SECURITY,
    topic: "Network security",
    blurb: "a managed stateful firewall with intrusion prevention applied at the VPC boundary",
  },
  {
    name: "Amazon GuardDuty",
    match: ["guardduty"],
    domain: SECURITY,
    topic: "Threat detection",
    blurb: "continuously analyses CloudTrail, VPC Flow Logs and DNS logs with threat intelligence to detect malicious activity, with no agent to install",
  },
  {
    name: "Amazon Inspector",
    match: ["amazon inspector", "inspector"],
    domain: SECURITY,
    topic: "Vulnerability management",
    blurb: "automatically scans EC2 instances, container images and Lambda functions for known software vulnerabilities and unintended network exposure",
  },
  {
    name: "Amazon Macie",
    match: ["macie"],
    domain: SECURITY,
    topic: "Data protection",
    blurb: "uses machine learning to discover and classify sensitive data such as personal information stored in Amazon S3",
  },
  {
    name: "AWS Security Hub",
    match: ["security hub"],
    domain: SECURITY,
    topic: "Security posture",
    blurb: "aggregates and normalises findings from GuardDuty, Inspector, Macie and partner tools into one dashboard and scores them against security standards",
  },
  {
    name: "Amazon Detective",
    match: ["detective"],
    domain: SECURITY,
    topic: "Incident response",
    blurb: "builds a linked behaviour graph from logs and findings to help investigate the root cause of a security issue after it is detected",
  },
  {
    name: "AWS Artifact",
    match: ["artifact"],
    domain: SECURITY,
    topic: "Compliance",
    blurb: "the self-service portal for downloading AWS compliance reports such as SOC and ISO, and for accepting agreements",
  },
  {
    name: "AWS Audit Manager",
    match: ["audit manager"],
    domain: SECURITY,
    topic: "Compliance",
    blurb: "continuously collects evidence about your own workloads to simplify producing an audit report against a framework",
  },
  {
    name: "AWS Config",
    match: ["aws config"],
    domain: SECURITY,
    topic: "Configuration compliance",
    blurb: "records how resource configurations change over time and evaluates each change against rules to flag non-compliant resources",
  },
  {
    name: "AWS CloudTrail",
    match: ["cloudtrail"],
    domain: SECURITY,
    topic: "Auditing",
    blurb: "records every API call in the account including who made it, from which IP address and when, which makes it the service that answers who did this",
  },
  {
    name: "Amazon CloudWatch",
    match: ["cloudwatch logs", "cloudwatch alarm", "cloudwatch"],
    domain: TECH,
    topic: "Monitoring",
    blurb: "collects metrics, logs and alarms describing how resources and applications are performing, and can trigger actions when a threshold is breached",
  },
  {
    name: "AWS X-Ray",
    match: ["x-ray", "xray"],
    domain: TECH,
    topic: "Monitoring",
    blurb: "traces a request as it moves through a distributed application to show where latency and errors originate",
  },
  {
    name: "Amazon CodeGuru",
    match: ["codeguru"],
    domain: TECH,
    topic: "Developer tools",
    blurb: "reviews source code for defects and profiles running applications to find the most expensive lines of code",
  },
  {
    name: "AWS Health Dashboard",
    match: ["personal health dashboard", "service health dashboard", "health dashboard", "aws health"],
    domain: BILLING,
    topic: "Service health",
    blurb: "shows the status of AWS services, with the personalised view alerting you to events affecting your specific resources",
  },
  {
    name: "VPC Flow Logs",
    match: ["flow logs", "flow log"],
    domain: SECURITY,
    topic: "Network monitoring",
    blurb: "capture metadata about IP traffic going to and from network interfaces, useful for troubleshooting connectivity and investigating suspicious traffic",
  },
  {
    name: "AWS CloudFormation",
    match: ["cloudformation"],
    domain: TECH,
    topic: "Infrastructure as code",
    blurb: "provisions and updates infrastructure from declarative JSON or YAML templates so environments can be recreated identically",
  },
  {
    name: "AWS CDK",
    match: ["cloud development kit", "aws cdk"],
    domain: TECH,
    topic: "Infrastructure as code",
    blurb: "defines infrastructure using a general-purpose programming language and synthesises it into CloudFormation templates",
  },
  {
    name: "AWS Systems Manager",
    match: ["systems manager", "ssm", "session manager", "parameter store"],
    domain: TECH,
    topic: "Operations",
    blurb: "provides operational control of instances at scale, including patching, run commands, shell access without open ports, and parameter storage",
  },
  {
    name: "AWS OpsWorks",
    match: ["opsworks"],
    domain: TECH,
    topic: "Operations",
    blurb: "managed instances of the Chef and Puppet configuration management platforms",
  },
  {
    name: "AWS CodeCommit",
    match: ["codecommit"],
    domain: TECH,
    topic: "Developer tools",
    blurb: "private managed Git repositories hosted in AWS",
  },
  {
    name: "AWS CodeBuild",
    match: ["codebuild"],
    domain: TECH,
    topic: "Developer tools",
    blurb: "compiles source code, runs tests and produces deployable artifacts without managing build servers",
  },
  {
    name: "AWS CodeDeploy",
    match: ["codedeploy"],
    domain: TECH,
    topic: "Developer tools",
    blurb: "automates the rollout of application code to EC2, Lambda or ECS with controlled strategies and rollback",
  },
  {
    name: "AWS CodePipeline",
    match: ["codepipeline"],
    domain: TECH,
    topic: "Developer tools",
    blurb: "orchestrates the whole continuous delivery pipeline, chaining source, build, test and deploy stages",
  },
  {
    name: "AWS CodeArtifact",
    match: ["codeartifact"],
    domain: TECH,
    topic: "Developer tools",
    blurb: "a managed repository for software packages and their dependencies",
  },
  {
    name: "AWS Cloud9",
    match: ["cloud9"],
    domain: TECH,
    topic: "Developer tools",
    blurb: "a browser-based integrated development environment with the AWS tooling preinstalled",
  },
  {
    name: "AWS Amplify",
    match: ["amplify"],
    domain: TECH,
    topic: "Developer tools",
    blurb: "a toolchain for building and hosting full-stack web and mobile applications with managed backends",
  },
  {
    name: "AWS AppSync",
    match: ["appsync"],
    domain: TECH,
    topic: "Application integration",
    blurb: "a managed GraphQL API layer with real-time data synchronisation for applications",
  },
  {
    name: "Amazon API Gateway",
    match: ["api gateway"],
    domain: TECH,
    topic: "Application integration",
    blurb: "publishes, secures and throttles REST and WebSocket APIs, commonly as the front door to Lambda functions",
  },
  {
    name: "Amazon SQS",
    match: ["amazon sqs", "simple queue service", "sqs"],
    domain: TECH,
    topic: "Application integration",
    blurb: "a managed message queue that decouples components by letting a producer write messages that a consumer processes later",
  },
  {
    name: "Amazon SNS",
    match: ["amazon sns", "simple notification service", "sns"],
    domain: TECH,
    topic: "Application integration",
    blurb: "a publish and subscribe service that pushes a single message out to many subscribers such as queues, functions, email or SMS",
  },
  {
    name: "Amazon MQ",
    match: ["amazon mq"],
    domain: TECH,
    topic: "Application integration",
    blurb: "a managed broker for ActiveMQ and RabbitMQ, chosen when migrating an application that already speaks those protocols",
  },
  {
    name: "AWS Step Functions",
    match: ["step functions"],
    domain: TECH,
    topic: "Application integration",
    blurb: "coordinates multiple services into a visual state machine workflow with built-in error handling and retries",
  },
  {
    name: "Amazon EventBridge",
    match: ["eventbridge", "cloudwatch events"],
    domain: TECH,
    topic: "Application integration",
    blurb: "routes events between AWS services, custom applications and SaaS providers based on rules",
  },
  {
    name: "AWS Organizations",
    match: ["aws organizations", "organizations"],
    domain: BILLING,
    topic: "Account management",
    blurb: "centrally manages multiple AWS accounts, providing consolidated billing, volume discount aggregation and policy control through service control policies",
  },
  {
    name: "service control policy",
    match: ["service control polic", "scp"],
    domain: SECURITY,
    topic: "Multi-account governance",
    blurb: "sets the maximum permissions available to member accounts, acting as a ceiling that no identity inside the account can exceed",
  },
  {
    name: "consolidated billing",
    match: ["consolidated billing"],
    domain: BILLING,
    topic: "Account management",
    blurb: "combines usage across all accounts in an organization into one bill, so volume discounts and Reserved Instance benefits are shared",
  },
  {
    name: "AWS Control Tower",
    match: ["control tower"],
    domain: SECURITY,
    topic: "Multi-account governance",
    blurb: "sets up and governs a secure multi-account landing zone with pre-configured guardrails",
  },
  {
    name: "AWS Service Catalog",
    match: ["service catalog"],
    domain: TECH,
    topic: "Governance",
    blurb: "lets an organisation publish an approved list of products that users may deploy, keeping deployments within agreed standards",
  },
  {
    name: "AWS Resource Access Manager",
    match: ["resource access manager", "aws ram"],
    domain: TECH,
    topic: "Account management",
    blurb: "shares resources such as subnets and transit gateways between accounts without duplicating them",
  },
  {
    name: "AWS Cost Explorer",
    match: ["cost explorer"],
    domain: BILLING,
    topic: "Cost analysis",
    blurb: "visualises and analyses historic cost and usage, and forecasts future spend based on observed trends",
  },
  {
    name: "AWS Budgets",
    match: ["aws budgets", "budgets"],
    domain: BILLING,
    topic: "Cost control",
    blurb: "sets a cost or usage threshold and alerts you when actual or forecast spend is about to exceed it, which is the proactive counterpart to Cost Explorer",
  },
  {
    name: "AWS Cost and Usage Report",
    match: ["cost and usage report", "cost & usage report", "cur"],
    domain: BILLING,
    topic: "Cost analysis",
    blurb: "delivers the most detailed available breakdown of charges, line by line, into an S3 bucket for custom analysis",
  },
  {
    name: "cost allocation tags",
    match: ["cost allocation tag", "cost allocation"],
    domain: BILLING,
    topic: "Cost analysis",
    blurb: "key-value labels applied to resources and activated in the billing console so spend can be grouped by project, team or environment",
  },
  {
    name: "AWS Pricing Calculator",
    match: ["pricing calculator", "simple monthly calculator", "tco calculator"],
    domain: BILLING,
    topic: "Cost estimation",
    blurb: "estimates the cost of a planned architecture before anything is deployed",
  },
  {
    name: "Reserved Instances",
    match: ["reserved instance", "reserved capacity"],
    domain: BILLING,
    topic: "Pricing models",
    blurb: "a one or three year commitment to a specific instance configuration in exchange for a large discount over On-Demand pricing",
  },
  {
    name: "Savings Plans",
    match: ["savings plan"],
    domain: BILLING,
    topic: "Pricing models",
    blurb: "a commitment to a consistent hourly spend for one or three years, offering Reserved Instance level discounts with more flexibility across instance families and services",
  },
  {
    name: "Spot Instances",
    match: ["spot instance", "spot fleet", "spot"],
    domain: BILLING,
    topic: "Pricing models",
    blurb: "spare capacity at up to ninety percent off, which AWS can reclaim with two minutes notice, so it suits fault-tolerant and interruptible work",
  },
  {
    name: "On-Demand Instances",
    match: ["on-demand instance", "on demand instance", "on-demand"],
    domain: BILLING,
    topic: "Pricing models",
    blurb: "pay by the second with no commitment, best for unpredictable workloads and short-term testing",
  },
  {
    name: "Dedicated Hosts",
    match: ["dedicated host", "dedicated instance"],
    domain: BILLING,
    topic: "Pricing models",
    blurb: "a physical server allocated to a single customer, usually chosen to satisfy per-socket software licensing or strict compliance requirements",
  },
  {
    name: "AWS Free Tier",
    match: ["free tier"],
    domain: BILLING,
    topic: "Pricing models",
    blurb: "a set of always-free, twelve-month-free and short-term trial offers that let new customers explore services at no cost",
  },
  {
    name: "AWS Trusted Advisor",
    match: ["trusted advisor"],
    domain: BILLING,
    topic: "Optimisation guidance",
    blurb: "inspects the account and recommends improvements across cost optimisation, performance, security, fault tolerance and service quotas",
  },
  {
    name: "AWS Support plans",
    match: ["enterprise support", "business support", "developer support", "basic support", "enterprise on-ramp", "support plan"],
    domain: BILLING,
    topic: "Support",
    blurb: "four paid tiers with increasing response times and access, where a technical account manager comes only with Enterprise On-Ramp and Enterprise",
  },
  {
    name: "technical account manager",
    match: ["technical account manager", "tam"],
    domain: BILLING,
    topic: "Support",
    blurb: "a designated AWS contact providing proactive guidance, available only with the Enterprise On-Ramp and Enterprise Support plans",
  },
  {
    name: "AWS Professional Services",
    match: ["professional services"],
    domain: BILLING,
    topic: "Support",
    blurb: "a paid AWS consulting organisation that works alongside customer teams and partners to accelerate cloud adoption",
  },
  {
    name: "AWS Partner Network",
    match: ["partner network", "apn", "consulting partner", "technology partner"],
    domain: BILLING,
    topic: "Support",
    blurb: "the global community of certified consulting and technology partners that build on or resell AWS",
  },
  {
    name: "AWS Marketplace",
    match: ["marketplace"],
    domain: BILLING,
    topic: "Procurement",
    blurb: "a curated catalogue of third-party software that can be purchased and deployed with the charges appearing on the AWS bill",
  },
  {
    name: "AWS Well-Architected Framework",
    match: ["well-architected", "well architected"],
    domain: CONCEPT,
    topic: "Well-Architected Framework",
    blurb: "six pillars of design guidance covering operational excellence, security, reliability, performance efficiency, cost optimisation and sustainability",
  },
  {
    name: "AWS Cloud Adoption Framework",
    match: ["cloud adoption framework", "aws caf"],
    domain: CONCEPT,
    topic: "Cloud Adoption Framework",
    blurb: "organises cloud transformation into six perspectives, namely business, people, governance, platform, security and operations",
  },
  {
    name: "shared responsibility model",
    match: ["shared responsibility"],
    domain: SECURITY,
    topic: "Shared Responsibility Model",
    blurb: "AWS secures the cloud itself while the customer secures what they put in it, with the dividing line moving upward as the service becomes more managed",
  },
  {
    name: "Availability Zone",
    match: ["availability zone"],
    domain: CONCEPT,
    topic: "Global infrastructure",
    blurb: "one or more discrete data centres inside a Region with independent power and networking, so deploying across two of them removes a single point of failure",
  },
  {
    name: "AWS Region",
    match: ["aws region", "region"],
    domain: CONCEPT,
    topic: "Global infrastructure",
    blurb: "a geographic area containing multiple isolated Availability Zones, chosen based on compliance, latency, service availability and cost",
  },
  {
    name: "edge location",
    match: ["edge location"],
    domain: CONCEPT,
    topic: "Global infrastructure",
    blurb: "a CloudFront cache site placed close to users to reduce latency, far more numerous than Regions",
  },
  {
    name: "high availability",
    match: ["high availability", "highly available"],
    domain: CONCEPT,
    topic: "Reliability",
    blurb: "keeping a workload reachable through failures, normally achieved by running redundant resources across multiple Availability Zones",
  },
  {
    name: "fault tolerance",
    match: ["fault tolerance", "fault tolerant"],
    domain: CONCEPT,
    topic: "Reliability",
    blurb: "continuing to operate correctly even while a component is failed, which is a stronger guarantee than high availability",
  },
  {
    name: "elasticity",
    match: ["elasticity", "elastic"],
    domain: CONCEPT,
    topic: "Elasticity",
    blurb: "acquiring capacity when demand rises and releasing it when demand falls, so cost follows actual load",
  },
  {
    name: "scalability",
    match: ["scalability", "scale up and down", "scale in and out", "scalable"],
    domain: CONCEPT,
    topic: "Scalability",
    blurb: "the ability to handle growing demand by adding capacity, either horizontally by adding instances or vertically by enlarging one",
  },
  {
    name: "horizontal scaling",
    match: ["horizontal scal", "scaling horizontally", "scale out", "scaling out"],
    domain: CONCEPT,
    topic: "Scalability",
    blurb: "adding more instances of the same size, which is the cloud-preferred approach because it has no ceiling and improves availability",
  },
  {
    name: "vertical scaling",
    match: ["vertical scal", "scaling vertically"],
    domain: CONCEPT,
    topic: "Scalability",
    blurb: "increasing the size of a single instance, which is simple but bounded by the largest available instance type",
  },
  {
    name: "agility",
    match: ["agility"],
    domain: CONCEPT,
    topic: "Cloud value proposition",
    blurb: "the ability to provision resources in minutes rather than weeks, which lowers the cost of experimenting",
  },
  {
    name: "capital expenditure",
    match: ["capital expense", "capital expenditure", "capex"],
    domain: CONCEPT,
    topic: "Cloud economics",
    blurb: "large up-front spending on hardware, which moving to AWS replaces with variable operational expenditure tied to usage",
  },
  {
    name: "economies of scale",
    match: ["economies of scale"],
    domain: CONCEPT,
    topic: "Cloud economics",
    blurb: "aggregated usage across many customers lets AWS buy infrastructure more cheaply and pass part of the saving on as lower prices",
  },
  {
    name: "total cost of ownership",
    match: ["total cost of ownership", "tco"],
    domain: BILLING,
    topic: "Cloud economics",
    blurb: "the full comparison between running a data centre and running on AWS, including power, cooling, space, hardware refresh and staff",
  },
  {
    name: "loose coupling",
    match: ["loose coupling", "loosely coupled", "decoupl"],
    domain: CONCEPT,
    topic: "Design principles",
    blurb: "connecting components through queues or load balancers so the failure of one does not cascade into the others",
  },
  {
    name: "serverless",
    match: ["serverless"],
    domain: CONCEPT,
    topic: "Serverless",
    blurb: "a model where AWS manages all capacity, patching and scaling, leaving only code and configuration as the customer responsibility",
  },
  {
    name: "hybrid cloud",
    match: ["hybrid cloud", "hybrid deployment"],
    domain: CONCEPT,
    topic: "Deployment models",
    blurb: "connecting on-premises infrastructure to AWS so the two operate as one environment, usually over Direct Connect or a VPN",
  },
  {
    name: "Infrastructure as a Service",
    match: ["infrastructure as a service", "iaas"],
    domain: CONCEPT,
    topic: "Service models",
    blurb: "supplies raw compute, storage and networking, giving the most control and leaving the operating system to the customer",
  },
  {
    name: "Platform as a Service",
    match: ["platform as a service", "paas"],
    domain: CONCEPT,
    topic: "Service models",
    blurb: "hides the operating system so teams deploy code without managing the runtime underneath",
  },
  {
    name: "Software as a Service",
    match: ["software as a service", "saas"],
    domain: CONCEPT,
    topic: "Service models",
    blurb: "a finished application operated entirely by the provider, where the customer only manages their own data and users",
  },
  {
    name: "Amazon Rekognition",
    match: ["rekognition"],
    domain: TECH,
    topic: "Machine learning",
    blurb: "analyses images and video to detect objects, faces, text and unsafe content",
  },
  {
    name: "Amazon Transcribe",
    match: ["transcribe"],
    domain: TECH,
    topic: "Machine learning",
    blurb: "converts speech in audio into written text",
  },
  {
    name: "Amazon Polly",
    match: ["polly"],
    domain: TECH,
    topic: "Machine learning",
    blurb: "turns written text into lifelike speech",
  },
  {
    name: "Amazon Translate",
    match: ["translate"],
    domain: TECH,
    topic: "Machine learning",
    blurb: "performs machine translation between languages",
  },
  {
    name: "Amazon Comprehend",
    match: ["comprehend"],
    domain: TECH,
    topic: "Machine learning",
    blurb: "extracts sentiment, entities, key phrases and topics from text using natural language processing",
  },
  {
    name: "Amazon Lex",
    match: ["amazon lex", "lex"],
    domain: TECH,
    topic: "Machine learning",
    blurb: "builds conversational chatbots using the same technology as Alexa",
  },
  {
    name: "Amazon SageMaker",
    match: ["sagemaker"],
    domain: TECH,
    topic: "Machine learning",
    blurb: "an end-to-end platform for building, training and deploying custom machine learning models",
  },
  {
    name: "Amazon Textract",
    match: ["textract"],
    domain: TECH,
    topic: "Machine learning",
    blurb: "extracts text, forms and tables from scanned documents",
  },
  {
    name: "Amazon Kendra",
    match: ["kendra"],
    domain: TECH,
    topic: "Machine learning",
    blurb: "an intelligent enterprise search service that answers natural language questions over internal documents",
  },
  {
    name: "Amazon Forecast",
    match: ["forecast"],
    domain: TECH,
    topic: "Machine learning",
    blurb: "produces time-series forecasts such as demand or inventory predictions",
  },
  {
    name: "Amazon Personalize",
    match: ["personalize"],
    domain: TECH,
    topic: "Machine learning",
    blurb: "generates individualised product and content recommendations",
  },
  {
    name: "Amazon WorkSpaces",
    match: ["workspaces"],
    domain: TECH,
    topic: "End user computing",
    blurb: "managed virtual desktops delivered to users over the internet",
  },
  {
    name: "Amazon AppStream 2.0",
    match: ["appstream"],
    domain: TECH,
    topic: "End user computing",
    blurb: "streams a single desktop application to a browser without delivering a whole desktop",
  },
  {
    name: "Amazon Connect",
    match: ["amazon connect"],
    domain: TECH,
    topic: "Business applications",
    blurb: "a cloud contact centre that can be set up without telephony hardware",
  },
  {
    name: "Amazon SES",
    match: ["simple email service", "amazon ses"],
    domain: TECH,
    topic: "Business applications",
    blurb: "sends transactional and marketing email at scale",
  },
  {
    name: "AWS IoT Core",
    match: ["iot core", "iot"],
    domain: TECH,
    topic: "Internet of things",
    blurb: "connects and manages fleets of devices and routes their messages to AWS services",
  },
  {
    name: "AWS Elastic Disaster Recovery",
    match: ["elastic disaster recovery", "disaster recovery"],
    domain: TECH,
    topic: "Backup and recovery",
    blurb: "continuously replicates servers into AWS so they can be recovered quickly after an outage",
  },
  {
    name: "AWS Application Migration Service",
    match: ["application migration service", "server migration", "mgn"],
    domain: TECH,
    topic: "Migration",
    blurb: "automates lift and shift migration by replicating on-premises servers into AWS",
  },
  {
    name: "AWS Database Migration Service",
    match: ["database migration service", "aws dms", "dms"],
    domain: TECH,
    topic: "Migration",
    blurb: "migrates databases into AWS with minimal downtime, including between different engines",
  },
  {
    name: "AWS Migration Hub",
    match: ["migration hub"],
    domain: TECH,
    topic: "Migration",
    blurb: "tracks the progress of application migrations across multiple AWS and partner migration tools in one place",
  },
  {
    name: "AWS Management Console",
    match: ["management console", "aws console"],
    domain: TECH,
    topic: "Access methods",
    blurb: "the browser-based interface for managing AWS resources, best suited to exploration rather than repeatable automation",
  },
  {
    name: "AWS CLI",
    match: ["aws cli", "command line interface"],
    domain: TECH,
    topic: "Access methods",
    blurb: "a command line tool for controlling AWS services and scripting repeatable operations",
  },
  {
    name: "AWS SDK",
    match: ["aws sdk", "software development kit"],
    domain: TECH,
    topic: "Access methods",
    blurb: "language-specific libraries that let application code call AWS APIs directly",
  },
  {
    name: "AWS Fault Injection Service",
    match: ["fault injection"],
    domain: TECH,
    topic: "Reliability testing",
    blurb: "runs controlled chaos engineering experiments to verify how a workload behaves under failure",
  },
  {
    name: "AWS Compute Optimizer",
    match: ["compute optimizer"],
    domain: BILLING,
    topic: "Cost control",
    blurb: "analyses utilisation metrics and recommends better-sized resources to cut waste",
  },
  {
    name: "AWS License Manager",
    match: ["license manager"],
    domain: BILLING,
    topic: "Governance",
    blurb: "tracks and enforces software licence usage across AWS and on-premises environments",
  },
  {
    name: "AWS Ground Station",
    match: ["ground station"],
    domain: TECH,
    topic: "Specialised services",
    blurb: "rents satellite antenna time as a managed service",
  },
  {
    name: "AWS Device Farm",
    match: ["device farm"],
    domain: TECH,
    topic: "Developer tools",
    blurb: "tests mobile and web applications against real physical devices in the cloud",
  },
  {
    name: "least privilege",
    match: ["least privilege"],
    domain: SECURITY,
    topic: "Identity and access",
    blurb: "granting only the permissions a task actually requires and reviewing them regularly, so a compromised credential has a limited blast radius",
  },
  {
    name: "the root user",
    match: ["root user", "root account"],
    domain: SECURITY,
    topic: "Identity and access",
    blurb: "the unrestricted account owner whose permissions cannot be reduced, so it should be protected with MFA and then left unused for daily work",
  },
  {
    name: "encryption at rest",
    match: ["encryption at rest", "encrypted at rest", "server-side encryption"],
    domain: SECURITY,
    topic: "Encryption",
    blurb: "protects stored data so that reading the underlying disk or object yields ciphertext, normally using keys held in AWS KMS",
  },
  {
    name: "encryption in transit",
    match: ["encryption in transit", "in transit", "tls", "ssl"],
    domain: SECURITY,
    topic: "Encryption in transit",
    blurb: "protects data as it crosses the network, typically by terminating TLS at a load balancer or CloudFront distribution",
  },
  {
    name: "reliability",
    match: ["reliability"],
    domain: CONCEPT,
    topic: "Reliability",
    blurb: "the ability of a workload to perform its function correctly and to recover automatically from infrastructure disruption",
  },
  {
    name: "the Operational Excellence pillar",
    match: ["operational excellence"],
    domain: CONCEPT,
    topic: "Well-Architected Framework",
    blurb: "covers running and monitoring systems, making small reversible changes, and refining procedures after every operational event",
  },
  {
    name: "the Performance Efficiency pillar",
    match: ["performance efficiency"],
    domain: CONCEPT,
    topic: "Well-Architected Framework",
    blurb: "covers using computing resources efficiently and keeping that efficiency as demand and technology change",
  },
  {
    name: "the Cost Optimization pillar",
    match: ["cost optimization", "cost optimisation"],
    domain: CONCEPT,
    topic: "Well-Architected Framework",
    blurb: "covers avoiding unnecessary spend, matching supply to demand and measuring what each workload actually costs",
  },
  {
    name: "the Sustainability pillar",
    match: ["sustainability"],
    domain: CONCEPT,
    topic: "Well-Architected Framework",
    blurb: "covers minimising the environmental impact of a workload by maximising utilisation and choosing efficient resources",
  },
  {
    name: "durability",
    match: ["durability", "eleven nines", "99.999999999"],
    domain: TECH,
    topic: "Object storage",
    blurb: "the probability that stored data survives, which S3 achieves by replicating every object across multiple Availability Zones",
  },
  {
    name: "a service level agreement",
    match: ["service level agreement", "sla"],
    domain: BILLING,
    topic: "Service commitments",
    blurb: "the published availability commitment for a service, backed by service credits rather than by cash compensation",
  },
  {
    name: "service quotas",
    match: ["service quota", "service limit", "soft limit"],
    domain: TECH,
    topic: "Operations",
    blurb: "the default per-account ceilings on resource counts, most of which can be raised by request",
  },
  {
    name: "resource tagging",
    match: ["tagging", "resource tag", "tags"],
    domain: BILLING,
    topic: "Cost analysis",
    blurb: "key-value labels attached to resources so that cost, ownership and environment can be reported on later",
  },
  {
    name: "data residency",
    match: ["data residency", "data sovereignty", "data governance"],
    domain: SECURITY,
    topic: "Compliance",
    blurb: "the legal requirement that data stays inside a defined geography, which constrains Region choice before any other factor",
  },
  {
    name: "penetration testing",
    match: ["penetration test", "pen test"],
    domain: SECURITY,
    topic: "Compliance",
    blurb: "permitted against a defined list of services on your own resources without prior approval, subject to the AWS testing policy",
  },
  {
    name: "pay-as-you-go pricing",
    match: ["pay-as-you-go", "pay as you go", "pay only for what you use"],
    domain: BILLING,
    topic: "Pricing models",
    blurb: "charging only for resources actually consumed, with no up-front commitment and no penalty for stopping",
  },
];

export const FALLBACK_TOPICS = [
  { match: ["encrypt", "cipher", "at rest", "in transit"], topic: "Encryption", domain: SECURITY },
  { match: ["compliance", "audit", "hipaa", "gdpr", "pci", "iso 27001", "soc "], topic: "Compliance", domain: SECURITY },
  { match: ["least privilege", "password policy", "access key", "credential", "root user", "root account"], topic: "Identity and access", domain: SECURITY },
  { match: ["invoice", "bill", "billing", "charge", "pricing", "cost", "discount", "payment"], topic: "Billing and pricing", domain: BILLING },
  { match: ["support plan", "support case", "response time", "concierge"], topic: "Support", domain: BILLING },
  { match: ["latency", "throughput", "performance"], topic: "Performance efficiency", domain: CONCEPT },
  { match: ["availability", "failover", "redundan", "resilien", "recovery", "rto", "rpo", "reliab", "fault"], topic: "Reliability", domain: CONCEPT },
  { match: ["migrat", "lift and shift", "rehost", "refactor", "replatform"], topic: "Migration", domain: CONCEPT },
  { match: ["subnet", "route table", "cidr", "network", "firewall", "port"], topic: "Networking", domain: TECH },
  { match: ["database", "query", "table", "schema"], topic: "Databases", domain: TECH },
  { match: ["storage", "backup", "archive", "object", "volume"], topic: "Storage", domain: TECH },
  { match: ["monitor", "metric", "log", "alarm", "notification"], topic: "Monitoring", domain: TECH },
  { match: ["container", "docker", "kubernetes"], topic: "Containers", domain: TECH },
  { match: ["instance", "compute", "virtual machine", "server"], topic: "Compute", domain: TECH },
  { match: ["cloud computing", "benefit", "advantage", "on-premises", "data centre", "data center"], topic: "Cloud value proposition", domain: CONCEPT },
];
